name: build-espressif-ide-installer

on:
  workflow_call:
    inputs:
      esp_idf_version:
        required: true
        type: string
      espressif_ide_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      esp_idf_version:
        description: 'ESP-IDF version (e.g. 5.1.1)'
        required: true
        type: string
      espressif_ide_version:
        description: 'Espressif IDE version (e.g. 2.9.0)'
        required: true
        type: string

jobs:
  build-espressif-ide-installer:
    name: Build Installer
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inputs Logged
        run: |
          echo "Received Espressif IDE Version: ${{ github.event.inputs.espressif_ide_version }}"
          echo "Received ESP-IDF Version: ${{ github.event.inputs.esp_idf_version }}"

      - name: Map local long path to new drive
        id: map_path
        shell: pwsh
        run: subst "p:" "$env:GITHUB_WORKSPACE"

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Inno Setup Download plugin
        shell: pwsh
        run: Invoke-WebRequest -Uri https://github.com/espressif/inno-download-plugin/releases/download/v1.5.1/idpsetup-1.5.1.exe -OutFile idpsetup.exe; .\idpsetup.exe /SILENT; Sleep 5
      
      - name: Build Installer
        env:
          CERTIFICATE: ${{ secrets.CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        shell: pwsh
        working-directory: "P:"
        run: .\Build-Installer.ps1 -InstallerType espressif-ide -OfflineBranch "v${{ github.event.inputs.esp_idf_version }}" -EspressifIdeVersion "${{ github.event.inputs.espressif_ide_version }}"

      - name: Get installer size and store it to file
        run: |
          echo $(Get-ItemProperty -Path .\build\espressif-ide-setup-espressif-ide-with-esp-idf-${{ github.event.inputs.esp_idf_version }}.exe | Select-Object -ExpandProperty Length) > variables.txt
          echo "Installer size from variable is $(Get-Content variables.txt)"
